import type { DubPack } from "./types";
import { PALETTE } from "./colors";

export const DUB_PACKS: DubPack[] = [
  {
    id: "krusty-krab",
    title: "Is This the Krusty Krab?",
    description:
      "SpongeBob’s classic phone gag — Patrick answers, and nothing goes right. NO, THIS IS PATRICK!",
    creator: "canded · idek6",
    clipCount: 10,
    tags: ["comedy", "cartoon", "classic"],
    popular: true,
    playCount: 9999,
    createdAt: "2026-07-18",
    thumbnailColor: PALETTE.coral,
    thumbnailUrl: "/packs/krusty-krab/thumb.png",
    videoUrl: "/packs/krusty-krab/video.mp4",
    backingTrackUrl: "/packs/krusty-krab/backing.mp3",
    lines: [
      {
        id: "kk-1",
        speaker: "SPONGEBOB",
        text: "All you have to do is answer the phone!",
        startMs: 0,
        endMs: 1793,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-01.ogg",
      },
      {
        id: "kk-2",
        speaker: "PATRICK",
        text: "Aye aye, Cap-n!",
        startMs: 1793,
        endMs: 3839,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-02.ogg",
      },
      {
        id: "kk-3",
        speaker: "PHONE",
        text: "Is this the Krusty Krab?",
        startMs: 7079,
        endMs: 8809,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-03.ogg",
      },
      {
        id: "kk-4",
        speaker: "PATRICK",
        text: "No, this is Patrick",
        startMs: 8809,
        endMs: 10686,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-04.ogg",
      },
      {
        id: "kk-5",
        speaker: "PHONE",
        text: "Is this the Krusty Krab?",
        startMs: 13168,
        endMs: 14819,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-05.ogg",
      },
      {
        id: "kk-6",
        speaker: "PATRICK",
        text: "Noo, this is Patrick!",
        startMs: 14820,
        endMs: 17828,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-06.ogg",
      },
      {
        id: "kk-7",
        speaker: "PHONE",
        text: "Is this the Krusty Krab?",
        startMs: 21656,
        endMs: 23328,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-07.ogg",
      },
      {
        id: "kk-8",
        speaker: "PATRICK",
        text: "No! This is Patrick! [Grunt] I'm not a Krusty Krab.",
        startMs: 23329,
        endMs: 29634,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-08.ogg",
      },
      {
        id: "kk-9",
        speaker: "SPONGEBOB",
        text: "Uhh, Patrick, that's the name of the restaurant.",
        startMs: 29634,
        endMs: 32295,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-09.ogg",
      },
      {
        id: "kk-10",
        speaker: "PATRICK",
        text: "Huh? [Anger sound] Fish paste!",
        startMs: 32295,
        endMs: 35700,
        referenceAudioUrl: "/packs/krusty-krab/lines/line-10.ogg",
      },
    ],
  },
  {
    id: "you-turned-her-against-me",
    title: "You Turned Her Against Me",
    description:
      "Mustafar showdown — Anakin and Obi-Wan. Can you out-act this masterclass of cinema?",
    creator: "Pothas",
    clipCount: 17,
    tags: ["drama", "scifi", "duel"],
    popular: true,
    playCount: 4200,
    createdAt: "2026-08-01",
    thumbnailColor: PALETTE.coral,
    thumbnailUrl: "/packs/you-turned-her-against-me/thumb.png",
    videoUrl: "/packs/you-turned-her-against-me/video.mp4",
    backingTrackUrl: "/packs/you-turned-her-against-me/backing.ogg",
    lines: [
      {
        id: "sw-1",
        speaker: "ANAKIN",
        text: "You turned her against me...!",
        startMs: 9796,
        endMs: 12147,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-01.ogg",
      },
      {
        id: "sw-2",
        speaker: "OBI-WAN",
        text: "You have done that yourself!",
        startMs: 13303,
        endMs: 15654,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-02.ogg",
      },
      {
        id: "sw-3",
        speaker: "ANAKIN",
        text: "You will not take her from me!",
        startMs: 20436,
        endMs: 22656,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-03.ogg",
      },
      {
        id: "sw-4",
        speaker: "OBI-WAN",
        text: "Your anger and your lust for power have already done that.",
        startMs: 22604,
        endMs: 26836,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-04.ogg",
      },
      {
        id: "sw-5",
        speaker: "OBI-WAN",
        text: "You have allowed this... Dark Lord to twist your mind until now...",
        startMs: 30321,
        endMs: 35101,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-05.ogg",
      },
      {
        id: "sw-6",
        speaker: "OBI-WAN",
        text: "...Until now you have become the very thing you swore to destroy.",
        startMs: 36285,
        endMs: 39864,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-06.ogg",
      },
      {
        id: "sw-7",
        speaker: "ANAKIN",
        text: "Don't lecture me, Obi-Wan. I see through the lies of the Jedi...",
        startMs: 39788,
        endMs: 44568,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-07.ogg",
      },
      {
        id: "sw-8",
        speaker: "ANAKIN",
        text: "I do not fear the dark side as you do!",
        startMs: 45210,
        endMs: 47979,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-08.ogg",
      },
      {
        id: "sw-9",
        speaker: "ANAKIN",
        text: "I have brought peace... freedom... justice...",
        startMs: 49340,
        endMs: 53911,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-09.ogg",
      },
      {
        id: "sw-10",
        speaker: "ANAKIN",
        text: "...And security to my new empire.",
        startMs: 53844,
        endMs: 56900,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-10.ogg",
      },
      {
        id: "sw-11",
        speaker: "OBI-WAN",
        text: "Your new empire?",
        startMs: 57306,
        endMs: 59579,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-11.ogg",
      },
      {
        id: "sw-12",
        speaker: "ANAKIN",
        text: "Don't make me kill you...",
        startMs: 60207,
        endMs: 62506,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-12.ogg",
      },
      {
        id: "sw-13",
        speaker: "OBI-WAN",
        text: "Anakin, my allegiance is to the Republic, to DEMOCRACY!",
        startMs: 63435,
        endMs: 68163,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-13.ogg",
      },
      {
        id: "sw-14",
        speaker: "ANAKIN",
        text: "If you're not with me... then you're my enemy.",
        startMs: 69026,
        endMs: 73963,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-14.ogg",
      },
      {
        id: "sw-15",
        speaker: "OBI-WAN",
        text: "Only a Sith deals in absolutes.",
        startMs: 75741,
        endMs: 78588,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-15.ogg",
      },
      {
        id: "sw-16",
        speaker: "OBI-WAN",
        text: "I will do what I must.",
        startMs: 80788,
        endMs: 82512,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-16.ogg",
      },
      {
        id: "sw-17",
        speaker: "ANAKIN",
        text: "You will try...",
        startMs: 83874,
        endMs: 85500,
        referenceAudioUrl: "/packs/you-turned-her-against-me/lines/line-17.ogg",
      },
    ],
  },
  {
    id: "peaky-no-fighting",
    title: "Peaky Blinders — No Fighting",
    description:
      "Tommy’s wedding-day rules for the boys. No cocaine, no sports, no sucking petrol — and no fighting.",
    creator: "Pothas",
    clipCount: 26,
    tags: ["drama", "comedy", "british"],
    popular: true,
    playCount: 3800,
    createdAt: "2026-08-01",
    thumbnailColor: PALETTE.coral,
    thumbnailUrl: "/packs/peaky-no-fighting/thumb.png",
    videoUrl: "/packs/peaky-no-fighting/video.mp4",
    backingTrackUrl: "/packs/peaky-no-fighting/backing.mp3",
    lines: [
      {
        id: "pb-1",
        speaker: "THOMAS",
        text: "Right boys, you're all here...",
        startMs: 5731,
        endMs: 7617,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-01.mp3",
      },
      {
        id: "pb-2",
        speaker: "THOMAS",
        text: "Today... this is my fuckin' wedding day-",
        startMs: 10920,
        endMs: 13982,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-02.mp3",
      },
      {
        id: "pb-3",
        speaker: "JOHN",
        text: "Yeah - and you said we'd be in our bloody uniforms-",
        startMs: 13920,
        endMs: 16590,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-03.mp3",
      },
      {
        id: "pb-4",
        speaker: "THOMAS",
        text: "Nevertheless, John... despite the bad blood...",
        startMs: 17304,
        endMs: 21437,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-04.mp3",
      },
      {
        id: "pb-5",
        speaker: "THOMAS",
        text: "I'll have none of it on my carpet. Now for Grace's sake-",
        startMs: 21360,
        endMs: 25022,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-05.mp3",
      },
      {
        id: "pb-6",
        speaker: "THOMAS",
        text: "-Nothing will go wrong. Those BASTARDS, out there-",
        startMs: 24960,
        endMs: 28962,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-06.mp3",
      },
      {
        id: "pb-7",
        speaker: "THOMAS",
        text: "-Are our family. And if you fuckers...",
        startMs: 28880,
        endMs: 31837,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-07.mp3",
      },
      {
        id: "pb-8",
        speaker: "THOMAS",
        text: "...do anything to embarass her, your kin...",
        startMs: 31760,
        endMs: 35788,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-08.mp3",
      },
      {
        id: "pb-9",
        speaker: "THOMAS",
        text: "...Your cousins, your horses, your fuckin' kids-",
        startMs: 35720,
        endMs: 39121,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-09.mp3",
      },
      {
        id: "pb-10",
        speaker: "THOMAS",
        text: "You do ANYTHING...!",
        startMs: 39040,
        endMs: 40482,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-10.mp3",
      },
      {
        id: "pb-11",
        speaker: "ISIAH",
        text: "Tom-",
        startMs: 40400,
        endMs: 40745,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-11.mp3",
      },
      {
        id: "pb-12",
        speaker: "THOMAS",
        text: "To- WHAT!!",
        startMs: 40680,
        endMs: 42044,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-12.mp3",
      },
      {
        id: "pb-13",
        speaker: "ISIAH",
        text: "Waddabout snow?",
        startMs: 41960,
        endMs: 43141,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-13.mp3",
      },
      {
        id: "pb-14",
        speaker: "JOHN",
        text: "Yeah they're women of sport, I'll say that...",
        startMs: 43640,
        endMs: 45866,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-14.mp3",
      },
      {
        id: "pb-15",
        speaker: "THOMAS",
        text: "No, no, no... No cocaine.",
        startMs: 45800,
        endMs: 50142,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-15.mp3",
      },
      {
        id: "pb-16",
        speaker: "THOMAS",
        text: "No cocaine, no sports, no telling fortunes, no racing-",
        startMs: 51320,
        endMs: 56001,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-16.mp3",
      },
      {
        id: "pb-17",
        speaker: "THOMAS",
        text: "No fucking sucking petrol out of their fucking cars...",
        startMs: 55920,
        endMs: 60471,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-17.mp3",
      },
      {
        id: "pb-18",
        speaker: "THOMAS",
        text: "And you, Charlie! Stop spinning yarns about me, eh?",
        startMs: 61560,
        endMs: 64987,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-18.mp3",
      },
      {
        id: "pb-19",
        speaker: "CHARLIE",
        text: "Aw, I'm just tryin to sell ya to them, Tom.",
        startMs: 64906,
        endMs: 66949,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-19.mp3",
      },
      {
        id: "pb-20",
        speaker: "THOMAS",
        text: "But the main thing is... you bunch of fuckers...",
        startMs: 68640,
        endMs: 72642,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-20.mp3",
      },
      {
        id: "pb-21",
        speaker: "THOMAS",
        text: "Despite the provocation from the cavalry... no fighting.",
        startMs: 72560,
        endMs: 77163,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-21.mp3",
      },
      {
        id: "pb-22",
        speaker: "THOMAS",
        text: "Oi! No fighting.",
        startMs: 78560,
        endMs: 82484,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-22.mp3",
      },
      {
        id: "pb-23",
        speaker: "THOMAS",
        text: "No fucking fighting. No fighting-",
        startMs: 82400,
        endMs: 85305,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-23.mp3",
      },
      {
        id: "pb-24",
        speaker: "THOMAS",
        text: "NO. FUCKING. FIGHTING!",
        startMs: 86120,
        endMs: 90070,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-24.mp3",
      },
      {
        id: "pb-25",
        speaker: "THOMAS",
        text: "Good.",
        startMs: 91020,
        endMs: 91496,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-25.mp3",
      },
      {
        id: "pb-26",
        speaker: "THOMAS",
        text: "Get the f- off me",
        startMs: 92880,
        endMs: 94322,
        referenceAudioUrl: "/packs/peaky-no-fighting/lines/line-26.mp3",
      },
    ],
  },
];

export function getPackById(id: string): DubPack | undefined {
  return DUB_PACKS.find((p) => p.id === id);
}

export function sortPacks(
  packs: DubPack[],
  sort: "newest" | "most-played"
): DubPack[] {
  const sorted = [...packs];
  if (sort === "newest") {
    sorted.sort(
      (a, b) =>
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
    );
  } else {
    sorted.sort((a, b) => b.playCount - a.playCount);
  }
  return sorted;
}

export function searchPacks(packs: DubPack[], query: string): DubPack[] {
  const q = query.toLowerCase();
  if (!q) return packs;
  return packs.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.creator.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  );
}
