import type { DubPost, UserProfile } from "@/lib/types/social";

/** Current user for stars / follow (auth later). */
export const LOCAL_USER_ID = "local-user";

export const SEED_USERS: UserProfile[] = [
  {
    id: LOCAL_USER_ID,
    displayName: "You",
    handle: "@you",
    bio: "Local dubber — finish packs to climb the ranks.",
    avatarColor: "#FF5A36",
    avatarIcon: "cat",
    followersCount: 3,
    totalStars: 0,
  },
  {
    id: "user-mira",
    displayName: "Mira Vox",
    handle: "@miravox",
    bio: "Cartoon takes only. Krusty Krab forever.",
    avatarColor: "#2EC4B6",
    avatarIcon: "dog",
    followersCount: 128,
    totalStars: 842,
  },
  {
    id: "user-jax",
    displayName: "Jax Line",
    handle: "@jaxline",
    bio: "Drama packs · Peaky energy.",
    avatarColor: "#1B1B1B",
    avatarIcon: "bear",
    followersCount: 94,
    totalStars: 510,
  },
  {
    id: "user-nova",
    displayName: "Nova Stage",
    handle: "@novastage",
    bio: "Lights, camera, dub.",
    avatarColor: "#FFB703",
    avatarIcon: "rabbit",
    followersCount: 210,
    totalStars: 1204,
  },
  {
    id: "user-reed",
    displayName: "Reed Echo",
    handle: "@reedecho",
    bio: "Star Wars scenes hit different with a bad mic.",
    avatarColor: "#5C6BC0",
    avatarIcon: "gorilla",
    followersCount: 67,
    totalStars: 388,
  },
  {
    id: "user-cleo",
    displayName: "Cleo Mic",
    handle: "@cleomic",
    bio: "Sharing takes before coffee.",
    avatarColor: "#E63946",
    avatarIcon: "pig",
    followersCount: 41,
    totalStars: 196,
  },
];

export const SEED_POSTS: DubPost[] = [
  {
    id: "post-1",
    authorId: "user-mira",
    packId: "krusty-krab",
    packTitle: "Is This the Krusty Krab?",
    caption: "NO THIS IS PATRICK — take 12 finally landed.",
    starCount: 86,
    createdAt: "2026-08-20T14:00:00Z",
  },
  {
    id: "post-2",
    authorId: "user-reed",
    packId: "you-turned-her-against-me",
    packTitle: "You Turned Her Against Me",
    caption: "Went full theatrical. Neighbors complained.",
    starCount: 54,
    createdAt: "2026-08-21T09:30:00Z",
  },
  {
    id: "post-3",
    authorId: "user-jax",
    packId: "peaky-no-fighting",
    packTitle: "Peaky Blinders — No Fighting",
    caption: "By order of the Peaky Blinders (and my throat).",
    starCount: 112,
    createdAt: "2026-08-21T18:12:00Z",
  },
  {
    id: "post-4",
    authorId: "user-nova",
    packId: "krusty-krab",
    packTitle: "Is This the Krusty Krab?",
    caption: "Phone bit in one take. Patrick voice is a lifestyle.",
    starCount: 203,
    createdAt: "2026-08-22T11:00:00Z",
  },
  {
    id: "post-5",
    authorId: "user-cleo",
    packId: "you-turned-her-against-me",
    packTitle: "You Turned Her Against Me",
    caption: "Soft read vs shout-off — which side are you?",
    starCount: 31,
    createdAt: "2026-08-22T16:45:00Z",
  },
  {
    id: "post-6",
    authorId: "user-mira",
    packId: "peaky-no-fighting",
    packTitle: "Peaky Blinders — No Fighting",
    caption: "Tried the accent. Regret nothing.",
    starCount: 77,
    createdAt: "2026-08-23T08:20:00Z",
  },
  {
    id: "post-7",
    authorId: "user-jax",
    packId: "krusty-krab",
    packTitle: "Is This the Krusty Krab?",
    caption: "Multiplayer with roommates. Chaos.",
    starCount: 45,
    createdAt: "2026-08-23T20:05:00Z",
  },
  {
    id: "post-8",
    authorId: "user-reed",
    packId: "peaky-no-fighting",
    packTitle: "Peaky Blinders — No Fighting",
    caption: "No fighting in the streets — only in the booth.",
    starCount: 68,
    createdAt: "2026-08-24T12:00:00Z",
  },
  {
    id: "post-9",
    authorId: "user-nova",
    packId: "you-turned-her-against-me",
    packTitle: "You Turned Her Against Me",
    caption: "Stage lights optional. Emotion is not.",
    starCount: 91,
    createdAt: "2026-08-24T19:40:00Z",
  },
  {
    id: "post-10",
    authorId: "user-cleo",
    packId: "krusty-krab",
    packTitle: "Is This the Krusty Krab?",
    caption: "Morning warm-up: answer the phone wrong.",
    starCount: 22,
    createdAt: "2026-08-25T07:15:00Z",
  },
];
